### ISSUE TITLE
Request updates to subsequent code and articles

### ISSUE THREAD

**Issue by daodaoers** [Joao-Dionisio/An-optimization-model-for-power-transformer-maintenance#1]
There's something I don't understand.Request updates to subsequent code and articles，please

**Comment by Joao-Dionisio** [comment]
Hello, @daodaoers! I just uploaded the final version of the paper. Regarding the code, it might be a bit more difficult, as I have been modifying it for a related (but different) problem. 

If you have any questions, feel free to ask!
